spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/room8
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080